version: 2

project_name: dex

before:
  hooks:
    - cargo fetch --locked

builds:
  - id: dex
    builder: rust
    binary: dex
    flags:
      - --release
      - --locked
      - --bin=dex
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-pc-windows-gnullvm

archives:
  - ids:
      - dex
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
